vegetable1 = input('Введите 1 название: ')
vegetable2 = input('Введите 2 название: ')
vegetable3 = input('Введите 3 название: ')
print(str.lower(vegetable1), str.lower(vegetable2), str.lower(vegetable3))
print(str.upper(vegetable1), str.upper(vegetable2), str.upper(vegetable3))
print(str.capitalize(vegetable1), str.capitalize(vegetable2), str.capitalize(vegetable3))
quantity1 = input(f'Введите количество {vegetable1}: ')
quantity2 = input(f'Введите количество {vegetable2}: ')
quantity3 = input(f'Введите количество {vegetable3}: ')
print('{} - {} шт.'.format(vegetable1, quantity1))
print('{} - {} шт.'.format(vegetable2, quantity2))
print('{} - {} шт.'.format(vegetable3, quantity3))
